---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
- name: download redis
  get_url:
    url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
    dest: "/usr/local/src/redis-{{ redis_version }}.tar.gz"
    mode: 0644
- name: unpack redis
  unarchive:
    src: "/usr/local/src/redis-{{ redis_version }}.tar.gz"
    dest: "/usr/local/src"
    creates: "/usr/local/src/redis-{{ redis_version }}"
    copy: no
- name: compile redis
  command: make -j5
  args:
    chdir: "/usr/local/src/redis-{{ redis_version }}"
    creates: "/usr/local/src/redis-{{ redis_version }}/src/redis-server"
- name: install redis
  become: yes
  become_user: redis
  command: make PREFIX=/opt/redis install
  args:
    chdir: "/usr/local/src/redis-{{ redis_version }}"
    creates: /opt/redis/bin/redis-server
