---
- name: create redis group
  group:
    name: redis
    state: present
- name: create redis user
  user:
    name: redis
    group: redis
- name: create redis directory
  file:
    state: directory
    path: "{{ item }}"
    owner: redis
    group: redis
  with_items:
    - /opt/redis
    - /var/log/redis
    - /var/lib/redis
    - /etc/redis
