---
- name: add nginx repo
  apt_repository:
    repo: "ppa:nginx/stable"
- name: install nginx
  apt:
    name: "nginx"
    state: present
- name: copy nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: create ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
- name: generate dhparams.pem
  command: openssl dhparam -out dhparam.pem 4096
  args:
    chdir: /etc/ssl/certs
    creates: /etc/ssl/certs/dhparam.pem
