---
- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present
  with_items:
    - unzip
    - dnsmasq
- name: copy dnsmasq configuration
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
