---
- name: download consul
  get_url:
    url: "{{ consul_download }}"
    dest: "/tmp/{{ consul_archive }}"
    mode: 0644
  become: yes
  become_user: consul
- name: unpack consul
  unarchive:
    src: "/tmp/{{ consul_archive }}"
    dest: "{{ consul_home }}/bin"
    copy: no
  become: yes
  become_user: consul
- name: add consul to path through profile.d
  template:
    src: consul.sh.j2
    dest: /etc/profile.d/consul.sh
    mode: 0755
- name: check if config file already exists
  stat:
    path: "{{ consul_config_file }}"
  register: config_file
- name: install consul config file
  template:
    src: consul.json.j2
    dest: "{{ consul_config_file }}"
    owner: consul
    group: consul
    mode: 0755
  when: not config_file.stat.exists
  notify:
    - restart consul
- name: install consul supervisor config file
  template:
    src: consul.conf.j2
    dest: /etc/supervisord.d/consul.conf
- name: add consul to supervisor
  supervisorctl:
    name: consul
    state: present
