---
- name: check consul-template version
  command: "{{ consul_home }}/bin/consul-template --version"
  register: consul_template_installed_version
  ignore_errors: True
- name: download consul template
  become: yes
  become_user: consul
  get_url:
    url: "{{ consul_template_download }}"
    dest: "/tmp/{{ consul_template_archive }}"
    mode: 0644
  when: consul_template_installed_version|failed or consul_template_installed_version.stderr.find(consul_template_version) == -1
- name: unpack consul template
  become: yes
  become_user: consul
  unarchive:
    src: "/tmp/{{ consul_template_archive }}"
    dest: "{{ consul_home }}/bin"
    copy: no
  when: consul_template_installed_version|failed or consul_template_installed_version.stderr.find(consul_template_version) == -1
