---
- name: download consul-ui
  become: yes
  become_user: consul
  get_url:
    url: "{{ consul_ui_download }}"
    dest: "/tmp/{{ consul_ui_archive }}"
    mode: 0644
- name: unpack consul-ui
  become: yes
  become_user: consul
  unarchive:
    src: "/tmp/{{ consul_ui_archive }}"
    dest: "{{ consul_home }}"
    copy: no
- name: add consul nginx vhost
  template:
    src: consul.vhost.j2
    dest: /etc/nginx/sites-available/consul
- name: symlink consul nginx vhost
  file:
    state: link
    src: /etc/nginx/sites-available/consul
    path: /etc/nginx/sites-enabled/consul
  notify:
    - restart nginx
