---
- name: add consul to path through profile.d
  template:
    src: consul.sh.j2
    dest: /etc/profile.d/consul.sh
    mode: 0755
- name: install consul config file
  template:
    src: consul.json.j2
    dest: "{{ consul_config_file }}"
    owner: consul
    group: consul
    mode: 0755
  notify:
    - restart consul
- name: install consul supervisor config file
  template:
    src: consul.conf.j2
    dest: /etc/supervisord.d/consul.conf
- name: add consul to supervisor
  supervisorctl:
    name: consul
    state: present
