---
- name: copy supervisor configuration files
  become: yes
  become_user: consul
  template:
    src: supervisord.json.j2
    dest: "{{ consul_config_dir }}/supervisord.json"
  notify:
    - restart consul
- name: copy supervisor checks
  become: yes
  become_user: consul
  copy:
    src: supervisord-running.sh
    dest: "{{ consul_home }}/check_scripts/supervisord-running.sh"
    mode: 0755
  notify:
    - restart consul
