---
- name: install nagios-plugins-basic
  apt:
    name: nagios-plugins-basic
    state: present
- name: copy syschecks file
  become: yes
  become_user: consul
  copy:
    src: syschecks.sh
    dest: "{{ consul_config_dir }}/syschecks.json"
    mode: 0755
  notify:
    - restart consul
