---
- hosts: all
  become: yes
  become_user: root
  vars:
    deploy_user: ubuntu
    rubies:
      - 2.2.2
    global_ruby: 2.2.2
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - { role: digital_ocean, tags: ['digital_ocean'] }
    - { role: base, tags: ['base'] }
