---
- hosts: all
  become: yes
  become_user: root
  vars:
    deploy_user: vagrant
    rubies:
      - 2.2.2
    global_ruby: 2.2.2
    pythons:
      - 3.4.3
    global_python: 3.4.3
    consul_aware: true
    consul_is_ui: true
    consul_is_server: true
    consul_bootstrap_expect: 1
    running_on_ec2: false
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    # - { role: naked }
    # - { role: fast_apt }
    - { role: base, tags: ['base'] }
    - { role: java, tags: ['java'] }
    - { role: solr, tags: ['solr'] }
    - { role: supervisor, tags: ['supervisor'] }
    - { role: consul, tags: ['consul'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: beanstalkd, tags: ['beanstalkd'] }
    - { role: ruby, tags: ['ruby'] }
    # - { role: python, tags: ['python'] }
    - { role: miniconda, tags: ['miniconda'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: memcached, tags: ['memcached'] }
