---
- hosts: all
  sudo: true
  vars:
    deploy_user: vagrant
    rubies:
      - 2.2.1
    global_ruby: 2.2.1
    pythons:
      - 3.4.3
    global_python: 3.4.3
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
  roles:
    # - { role: fast_apt }
    - { role: base, tags: ['base'] }
    - { role: supervisor, tags: ['supervisor'] }
    - { role: beanstalkd, tags: ['beanstalkd'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: miniconda, tags: ['miniconda'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: postgresql, tags: ['postresql'] }
