---
- hosts: all
  sudo: true
  vars:
    deploy_user: vagrant
    rubies:
      - 2.2.1
    global_ruby: 2.2.1
    pythons:
      - 3.4.3
    global_python: 3.4.3
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
  roles:
    # - { role: fast_apt }
    - { role: base }
    - { role: ruby }
    - { role: miniconda, tags: ['miniconda'] }
    - { role: nginx }
    - { role: postgresql }
