---
- name: move secrets to the right place
  command: cp etc/smokeping_secrets.dist /etc/smokeping/smokeping_secrets
  args:
    chdir: /opt/smokeping
    creates: /etc/smokeping/smokeping_secrets
- name: define secure mode to secrets
  file:
    path: /etc/smokeping/smokeping_secrets
    mode: 0600
    owner: smokeping
    group: smokeping
- name: synchronize htdocs contents to var www
  shell: cp -R htdocs/cropper /var/www/smokeping/
  args:
    chdir: /opt/smokeping
    creates: /var/www/smokeping/cropper
- name: copy the fcgi script
  copy:
    src: smokeping.fcgi
    dest: /var/www/smokeping/smokeping.fcgi
    mode: 0755
- name: copy the basepage.html file
  command: cp etc/basepage.html.dist /var/www/smokeping/basepage.html
  args:
    chdir: /opt/smokeping
    creates: /var/www/smokeping/basepage.html
- name: copy the config file
  template:
    src: config.j2
    dest: /etc/smokeping/config
- name: copy the nginx vhost
  copy:
    src: smokeping.vhost
    dest: /etc/nginx/sites-available/smokeping
- name: symlink smokeping nginx vhost
  file:
    state: link
    src: /etc/nginx/sites-available/smokeping
    path: /etc/nginx/sites-enabled/smokeping
  notify:
    - restart nginx
- name: install smokeping supervisor config file
  template:
    src: smokeping.supervisor.conf.j2
    dest: /etc/supervisord.d/smokeping.conf
- name: add smokeping to supervisor
  supervisorctl:
    name: smokeping
    state: present
- meta: flush_handlers
