---
- name: install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-software-properties
    - build-essential
    - curl
    - git
    - htop
    - ntp
    - unzip
    - vim
    - unattended-upgrades
    - dkms
