---
- name: configure ssh server
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
  with_items:
    - { line: "AllowAgentForwarding yes", regexp: "^AllowAgentForwarding yes$" }
    - { line: "ClientAliveInterval 60", regexp: "^ClientAliveInterval 60$" }
    - { line: "ClientAliveCountMax 60", regexp: "^ClientAliveCountMax 60$" }
  notify:
    - restart ssh
