---
- name: configure unattended upgrades
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "10periodic", dest: "/etc/apt/apt.conf.d/10periodic" }
    - { src: "50unattended-upgrades", dest: "/etc/apt/apt.conf.d/50unattended-upgrades" }
