---
- name: configure unattended upgrades
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
