---
- name: download miniconda
  become: yes
  become_user: "{{ deploy_user }}"
  get_url:
    url: http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
    mode: 0755
- name: install miniconda
  become: yes
  become_user: "{{ deploy_user }}"
  shell: /tmp/miniconda.sh -b -p ~/miniconda
  args:
    creates: ~/miniconda
    executable: /bin/bash
- name: enable bash loading
  become: yes
  become_user: "{{ deploy_user }}"
  lineinfile:
    dest: ~/.profile
    line: "export PATH=~/miniconda/bin:$PATH"
    regexp: "miniconda"
    insertafter: EOF
- name: update conda
  become: yes
  become_user: "{{ deploy_user }}"
  shell: ~/miniconda/bin/conda update conda --yes -q
  args:
    executable: /bin/bash
- name: install pip
  become: yes
  become_user: "{{ deploy_user }}"
  shell: ~/miniconda/bin/conda install pip --yes -q
  args:
    executable: /bin/bash
